- hosts: all
  become: true
  pre_tasks:
    - name: Update Repository Index (CentOS)
      tags: always
      dnf:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install Epel-release (CentOS)
      tags: always
      dnf:
        name: epel-release
      when: ansible_distribution == "CentOS"

    - name: Install Update (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: ubuntu_server
  become: true
  roles:
    - ubuntu_server

- hosts: centos_server
  become: true
  roles:
    - centos_server

